### PR TITLE
use nvfetcher for automated dependency updating

### PR DESCRIPTION
**Pull request by Gerg-L**
This PR moves all the sources to nvfetcher and adds spotify and spicetify-cli to spicePkgs so you no longer have to rely on the nixpkgs counterparts

the devShell adds an "update" command which should automatically update every source and input 
I also added a .envrc, added .direnv to the .gitignore for nix-direnv

Let me know any thoughts you have!

### CODE REVIEW

**Comment by the-argus** [comment]
@Gerg-L Why do you feel it necessary to have our own instance of spotify? I personally don't know much about how spotify is packaged, I can read over it and run the update command but if there are breaking changes down the line I would prefer to leave that to upstream. I haven't had any problems with upstream, either, so why fix it if it isn't broken?

**Comment by Gerg-L** [comment]
It was more of a "Can I do this" rather than a "Should I do this" moment with adding Spotify and Spicetify-cli.
My main thought was newer = better :P
> I personally don't know much about how spotify is packaged

It just copying binary files from the snap package and linking a few binaries not too bad, but i understand what you mean

**Comment by Gerg-L** [comment]
alright i removed spotfiy and spicetify from spicePkgs, and with those gone the update script is no longer needed as those took some jank to update now just a simple ``nvfetcher`` in the /pkgs directory will update all sources

**Comment by the-argus** [comment]
Okay, I like these changes, and I think they may fix #20
Merging.

**Pull request merged**
