### PR TITLE
Add autoupdate support and add new themes

### PR DESCRIPTION
**Pull request by A1ca7raz**

### CODE REVIEW

**Comment by luisnquin** [comment]
Just what I needed, thanks!

**Comment by the-argus** [comment]
@a1ca7raz I like this, but I don't want to push any packages that don't build. Right now the flake has the output `checks.x86_64-linux.default`, which I would like to be assured builds successfully before CI makes any changes. Could you add that to the workflow?

**Comment by A1ca7raz** [comment]
> @a1ca7raz I like this, but I don't want to push any packages that don't build. Right now the flake has the output `checks.x86_64-linux.default`, which I would like to be assured builds successfully before CI makes any changes. Could you add that to the workflow?

Done.

**Comment by the-argus** [comment]
Thanks so much. Merging now.

**Pull request merged**
